    package ouenerguate.dictamen;
    
    /**
     * This class was automatically generated by the data modeler tool.
     */
    
    @javax.persistence.Entity
    public class ObjectCoordenadas implements java.io.Serializable
    {
    
       static final long serialVersionUID = 1L;
    
       @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "OBJECTCOORDENADAS_ID_GENERATOR")
       @javax.persistence.Id
       @javax.persistence.SequenceGenerator(sequenceName = "OBJECTCOORDENADAS_ID_SEQ", name = "OBJECTCOORDENADAS_ID_GENERATOR")
       private java.lang.Long id;
    
       @org.kie.api.definition.type.Label("caso")
       private java.lang.String caso;
    
       @org.kie.api.definition.type.Label("xmts01")
       private java.lang.String xmts01;
       @org.kie.api.definition.type.Label("ymts01")
       private java.lang.String ymts01;
       @org.kie.api.definition.type.Label("xmts02")
       private java.lang.String xmts02;
       @org.kie.api.definition.type.Label("ymts02")
       private java.lang.String ymts02;
       @org.kie.api.definition.type.Label("xmts03")
       private java.lang.String xmts03;
       @org.kie.api.definition.type.Label("ymts03")
       private java.lang.String ymts03;
       @org.kie.api.definition.type.Label("xmts04")
       private java.lang.String xmts04;
       @org.kie.api.definition.type.Label("ymts04")
       private java.lang.String ymts04;
       @org.kie.api.definition.type.Label("xmts05")
       private java.lang.String xmts05;
       @org.kie.api.definition.type.Label("ymts05")
       private java.lang.String ymts05;
       @org.kie.api.definition.type.Label("xmts06")
       private java.lang.String xmts06;
       @org.kie.api.definition.type.Label("ymts06")
       private java.lang.String ymts06;
       @org.kie.api.definition.type.Label("xmts07")
       private java.lang.String xmts07;
       @org.kie.api.definition.type.Label("ymts07")
       private java.lang.String ymts07;
       @org.kie.api.definition.type.Label("xmts08")
       private java.lang.String xmts08;
       @org.kie.api.definition.type.Label("ymts08")
       private java.lang.String ymts08;
       @org.kie.api.definition.type.Label("xmts09")
       private java.lang.String xmts09;
       @org.kie.api.definition.type.Label("ymts09")
       private java.lang.String ymts09;
       @org.kie.api.definition.type.Label("xmts10")
       private java.lang.String xmts10;
       @org.kie.api.definition.type.Label("ymts10")
       private java.lang.String ymts10;
       @org.kie.api.definition.type.Label("xmts11")
       private java.lang.String xmts11;
       @org.kie.api.definition.type.Label("ymts11")
       private java.lang.String ymts11;
       @org.kie.api.definition.type.Label("xmts12")
       private java.lang.String xmts12;
       @org.kie.api.definition.type.Label("ymts12")
       private java.lang.String ymts12;
       @org.kie.api.definition.type.Label("xmts13")
       private java.lang.String xmts13;
       @org.kie.api.definition.type.Label("ymts13")
       private java.lang.String ymts13;
       @org.kie.api.definition.type.Label("xmts14")
       private java.lang.String xmts14;
       @org.kie.api.definition.type.Label("ymts14")
       private java.lang.String ymts14;
       @org.kie.api.definition.type.Label("xmts15")
       private java.lang.String xmts15;
       @org.kie.api.definition.type.Label("ymts15")
       private java.lang.String ymts15;
       @org.kie.api.definition.type.Label("xmts16")
       private java.lang.String xmts16;
       @org.kie.api.definition.type.Label("ymts16")
       private java.lang.String ymts16;
       @org.kie.api.definition.type.Label("xmts17")
       private java.lang.String xmts17;
       @org.kie.api.definition.type.Label("ymts17")
       private java.lang.String ymts17;
       @org.kie.api.definition.type.Label("xmts18")
       private java.lang.String xmts18;
       @org.kie.api.definition.type.Label("ymts18")
       private java.lang.String ymts18;
       @org.kie.api.definition.type.Label("xmts19")
       private java.lang.String xmts19;
       @org.kie.api.definition.type.Label("ymts19")
       private java.lang.String ymts19;
       @org.kie.api.definition.type.Label("xmts20")
       private java.lang.String xmts20;
       @org.kie.api.definition.type.Label("ymts20")
       private java.lang.String ymts20;
    
       @org.kie.api.definition.type.Label("tipoMedicion")
       private java.lang.String tipoMedicion;
    
       @org.kie.api.definition.type.Label("matricula")
       private java.lang.String matricula;
    
       @org.kie.api.definition.type.Label("faseUtilizar")
       private java.lang.String faseUtilizar;
    
       @org.kie.api.definition.type.Label("nombreIng")
       private java.lang.String nombreIng;
    
       @org.kie.api.definition.type.Label("numColegiado")
       private java.lang.String numColegiado;
    
       @org.kie.api.definition.type.Label("telefonoIng")
       private java.lang.String telefonoIng;
    
       @org.kie.api.definition.type.Label("numConsColegiado")
       private java.lang.String numConsColegiado;
    
       @org.kie.api.definition.type.Label("fechaVenColegiado")
       private java.lang.String fechaVenColegiado;
    
       @org.kie.api.definition.type.Label("breveDesc")
       private java.lang.String breveDesc;
    
       @org.kie.api.definition.type.Label("cantidadPoste1")
       private java.lang.String cantidadPoste1;
    
       @org.kie.api.definition.type.Label("longitudPoste1")
       private java.lang.String longitudPoste1;
    
       @org.kie.api.definition.type.Label("materialPoste1")
       private java.lang.String materialPoste1;
    
       @org.kie.api.definition.type.Label("cantidadPoste2")
       private java.lang.String cantidadPoste2;
    
       @org.kie.api.definition.type.Label("longitudPoste2")
       private java.lang.String longitudPoste2;
    
       @org.kie.api.definition.type.Label("materialPoste2")
       private java.lang.String materialPoste2;
    
       @org.kie.api.definition.type.Label("cantidadPoste3")
       private java.lang.String cantidadPoste3;
    
       @org.kie.api.definition.type.Label("longitudPoste3")
       private java.lang.String longitudPoste3;
    
       @org.kie.api.definition.type.Label("materialPoste3")
       private java.lang.String materialPoste3;
    
       @org.kie.api.definition.type.Label("cantidadPoste4")
       private java.lang.String cantidadPoste4;
    
       @org.kie.api.definition.type.Label("longitudPoste4")
       private java.lang.String longitudPoste4;
    
       @org.kie.api.definition.type.Label("materialPoste4")
       private java.lang.String materialPoste4;
    
       @org.kie.api.definition.type.Label("cantidadPoste5")
       private java.lang.String cantidadPoste5;
    
       @org.kie.api.definition.type.Label("longitudPoste5")
       private java.lang.String longitudPoste5;
    
       @org.kie.api.definition.type.Label("materialPoste5")
       private java.lang.String materialPoste5;
    
       @org.kie.api.definition.type.Label("cantidadPoste6")
       private java.lang.String cantidadPoste6;
    
       @org.kie.api.definition.type.Label("longitudPoste6")
       private java.lang.String longitudPoste6;
    
       @org.kie.api.definition.type.Label("materialPoste6")
       private java.lang.String materialPoste6;
    
       @org.kie.api.definition.type.Label("resolucion")
       private java.lang.String resolucion;
    
       @org.kie.api.definition.type.Label("xmts21")
       private java.lang.String xmts21;
    
       @org.kie.api.definition.type.Label("ymts21")
       private java.lang.String ymts21;
    
       @org.kie.api.definition.type.Label("xmts22")
       private java.lang.String xmts22;
    
       @org.kie.api.definition.type.Label("ymts22")
       private java.lang.String ymts22;
    
       @org.kie.api.definition.type.Label("xmts23")
       private java.lang.String xmts23;
    
       @org.kie.api.definition.type.Label("ymts23")
       private java.lang.String ymts23;
    
       @org.kie.api.definition.type.Label("xmts24")
       private java.lang.String xmts24;
    
       @org.kie.api.definition.type.Label("xmts25")
       private java.lang.String xmts25;
    
       @org.kie.api.definition.type.Label("ymts25")
       private java.lang.String ymts25;
    
       @org.kie.api.definition.type.Label("xmts26")
       private java.lang.String xmts26;
    
       @org.kie.api.definition.type.Label("ymts26")
       private java.lang.String ymts26;
    
       @org.kie.api.definition.type.Label("xmts27")
       private java.lang.String xmts27;
    
       @org.kie.api.definition.type.Label("xmts28")
       private java.lang.String xmts28;
    
       @org.kie.api.definition.type.Label("ymts28")
       private java.lang.String ymts28;
    
       @org.kie.api.definition.type.Label("xmts29")
       private java.lang.String xmts29;
    
       @org.kie.api.definition.type.Label("ymts29")
       private java.lang.String ymts29;
    
       @org.kie.api.definition.type.Label("xmts30")
       private java.lang.String xmts30;
    
       @org.kie.api.definition.type.Label("ymts30")
       private java.lang.String ymts30;
    
       @org.kie.api.definition.type.Label(value = "ymts24")
       private java.lang.String ymts24;
    
       @org.kie.api.definition.type.Label(value = "ymts27")
       private java.lang.String ymts27;
    
       public ObjectCoordenadas()
       {
       }
    
       public java.lang.Long getId()
       {
          return this.id;
       }
    
       public void setId(java.lang.Long id)
       {
          this.id = id;
       }
    
       public java.lang.String getCaso()
       {
          return this.caso;
       }
    
       public void setCaso(java.lang.String caso)
       {
          this.caso = caso;
       }
    
       public java.lang.String getXmts01()
       {
          return this.xmts01;
       }
    
       public void setXmts01(java.lang.String xmts01)
       {
          this.xmts01 = xmts01;
       }
    
       public java.lang.String getYmts01()
       {
          return this.ymts01;
       }
    
       public void setYmts01(java.lang.String ymts01)
       {
          this.ymts01 = ymts01;
       }
    
       public java.lang.String getXmts02()
       {
          return this.xmts02;
       }
    
       public void setXmts02(java.lang.String xmts02)
       {
          this.xmts02 = xmts02;
       }
    
       public java.lang.String getYmts02()
       {
          return this.ymts02;
       }
    
       public void setYmts02(java.lang.String ymts02)
       {
          this.ymts02 = ymts02;
       }
    
       public java.lang.String getXmts03()
       {
          return this.xmts03;
       }
    
       public void setXmts03(java.lang.String xmts03)
       {
          this.xmts03 = xmts03;
       }
    
       public java.lang.String getYmts03()
       {
          return this.ymts03;
       }
    
       public void setYmts03(java.lang.String ymts03)
       {
          this.ymts03 = ymts03;
       }
    
       public java.lang.String getXmts04()
       {
          return this.xmts04;
       }
    
       public void setXmts04(java.lang.String xmts04)
       {
          this.xmts04 = xmts04;
       }
    
       public java.lang.String getYmts04()
       {
          return this.ymts04;
       }
    
       public void setYmts04(java.lang.String ymts04)
       {
          this.ymts04 = ymts04;
       }
    
       public java.lang.String getXmts05()
       {
          return this.xmts05;
       }
    
       public void setXmts05(java.lang.String xmts05)
       {
          this.xmts05 = xmts05;
       }
    
       public java.lang.String getYmts05()
       {
          return this.ymts05;
       }
    
       public void setYmts05(java.lang.String ymts05)
       {
          this.ymts05 = ymts05;
       }
    
       public java.lang.String getXmts06()
       {
          return this.xmts06;
       }
    
       public void setXmts06(java.lang.String xmts06)
       {
          this.xmts06 = xmts06;
       }
    
       public java.lang.String getYmts06()
       {
          return this.ymts06;
       }
    
       public void setYmts06(java.lang.String ymts06)
       {
          this.ymts06 = ymts06;
       }
    
       public java.lang.String getXmts07()
       {
          return this.xmts07;
       }
    
       public void setXmts07(java.lang.String xmts07)
       {
          this.xmts07 = xmts07;
       }
    
       public java.lang.String getYmts07()
       {
          return this.ymts07;
       }
    
       public void setYmts07(java.lang.String ymts07)
       {
          this.ymts07 = ymts07;
       }
    
       public java.lang.String getXmts08()
       {
          return this.xmts08;
       }
    
       public void setXmts08(java.lang.String xmts08)
       {
          this.xmts08 = xmts08;
       }
    
       public java.lang.String getYmts08()
       {
          return this.ymts08;
       }
    
       public void setYmts08(java.lang.String ymts08)
       {
          this.ymts08 = ymts08;
       }
    
       public java.lang.String getXmts09()
       {
          return this.xmts09;
       }
    
       public void setXmts09(java.lang.String xmts09)
       {
          this.xmts09 = xmts09;
       }
    
       public java.lang.String getYmts09()
       {
          return this.ymts09;
       }
    
       public void setYmts09(java.lang.String ymts09)
       {
          this.ymts09 = ymts09;
       }
    
       public java.lang.String getXmts10()
       {
          return this.xmts10;
       }
    
       public void setXmts10(java.lang.String xmts10)
       {
          this.xmts10 = xmts10;
       }
    
       public java.lang.String getYmts10()
       {
          return this.ymts10;
       }
    
       public void setYmts10(java.lang.String ymts10)
       {
          this.ymts10 = ymts10;
       }
    
       public java.lang.String getXmts11()
       {
          return this.xmts11;
       }
    
       public void setXmts11(java.lang.String xmts11)
       {
          this.xmts11 = xmts11;
       }
    
       public java.lang.String getYmts11()
       {
          return this.ymts11;
       }
    
       public void setYmts11(java.lang.String ymts11)
       {
          this.ymts11 = ymts11;
       }
    
       public java.lang.String getXmts12()
       {
          return this.xmts12;
       }
    
       public void setXmts12(java.lang.String xmts12)
       {
          this.xmts12 = xmts12;
       }
    
       public java.lang.String getYmts12()
       {
          return this.ymts12;
       }
    
       public void setYmts12(java.lang.String ymts12)
       {
          this.ymts12 = ymts12;
       }
    
       public java.lang.String getXmts13()
       {
          return this.xmts13;
       }
    
       public void setXmts13(java.lang.String xmts13)
       {
          this.xmts13 = xmts13;
       }
    
       public java.lang.String getYmts13()
       {
          return this.ymts13;
       }
    
       public void setYmts13(java.lang.String ymts13)
       {
          this.ymts13 = ymts13;
       }
    
       public java.lang.String getXmts14()
       {
          return this.xmts14;
       }
    
       public void setXmts14(java.lang.String xmts14)
       {
          this.xmts14 = xmts14;
       }
    
       public java.lang.String getYmts14()
       {
          return this.ymts14;
       }
    
       public void setYmts14(java.lang.String ymts14)
       {
          this.ymts14 = ymts14;
       }
    
       public java.lang.String getXmts15()
       {
          return this.xmts15;
       }
    
       public void setXmts15(java.lang.String xmts15)
       {
          this.xmts15 = xmts15;
       }
    
       public java.lang.String getYmts15()
       {
          return this.ymts15;
       }
    
       public void setYmts15(java.lang.String ymts15)
       {
          this.ymts15 = ymts15;
       }
    
       public java.lang.String getXmts16()
       {
          return this.xmts16;
       }
    
       public void setXmts16(java.lang.String xmts16)
       {
          this.xmts16 = xmts16;
       }
    
       public java.lang.String getYmts16()
       {
          return this.ymts16;
       }
    
       public void setYmts16(java.lang.String ymts16)
       {
          this.ymts16 = ymts16;
       }
    
       public java.lang.String getXmts17()
       {
          return this.xmts17;
       }
    
       public void setXmts17(java.lang.String xmts17)
       {
          this.xmts17 = xmts17;
       }
    
       public java.lang.String getYmts17()
       {
          return this.ymts17;
       }
    
       public void setYmts17(java.lang.String ymts17)
       {
          this.ymts17 = ymts17;
       }
    
       public java.lang.String getXmts18()
       {
          return this.xmts18;
       }
    
       public void setXmts18(java.lang.String xmts18)
       {
          this.xmts18 = xmts18;
       }
    
       public java.lang.String getYmts18()
       {
          return this.ymts18;
       }
    
       public void setYmts18(java.lang.String ymts18)
       {
          this.ymts18 = ymts18;
       }
    
       public java.lang.String getXmts19()
       {
          return this.xmts19;
       }
    
       public void setXmts19(java.lang.String xmts19)
       {
          this.xmts19 = xmts19;
       }
    
       public java.lang.String getYmts19()
       {
          return this.ymts19;
       }
    
       public void setYmts19(java.lang.String ymts19)
       {
          this.ymts19 = ymts19;
       }
    
       public java.lang.String getXmts20()
       {
          return this.xmts20;
       }
    
       public void setXmts20(java.lang.String xmts20)
       {
          this.xmts20 = xmts20;
       }
    
       public java.lang.String getYmts20()
       {
          return this.ymts20;
       }
    
       public void setYmts20(java.lang.String ymts20)
       {
          this.ymts20 = ymts20;
       }
    
       public java.lang.String getTipoMedicion()
       {
          return this.tipoMedicion;
       }
    
       public void setTipoMedicion(java.lang.String tipoMedicion)
       {
          this.tipoMedicion = tipoMedicion;
       }
    
       public java.lang.String getMatricula()
       {
          return this.matricula;
       }
    
       public void setMatricula(java.lang.String matricula)
       {
          this.matricula = matricula;
       }
    
       public java.lang.String getFaseUtilizar()
       {
          return this.faseUtilizar;
       }
    
       public void setFaseUtilizar(java.lang.String faseUtilizar)
       {
          this.faseUtilizar = faseUtilizar;
       }
    
       public java.lang.String getNombreIng()
       {
          return this.nombreIng;
       }
    
       public void setNombreIng(java.lang.String nombreIng)
       {
          this.nombreIng = nombreIng;
       }
    
       public java.lang.String getNumColegiado()
       {
          return this.numColegiado;
       }
    
       public void setNumColegiado(java.lang.String numColegiado)
       {
          this.numColegiado = numColegiado;
       }
    
       public java.lang.String getTelefonoIng()
       {
          return this.telefonoIng;
       }
    
       public void setTelefonoIng(java.lang.String telefonoIng)
       {
          this.telefonoIng = telefonoIng;
       }
    
       public java.lang.String getNumConsColegiado()
       {
          return this.numConsColegiado;
       }
    
       public void setNumConsColegiado(java.lang.String numConsColegiado)
       {
          this.numConsColegiado = numConsColegiado;
       }
    
       public java.lang.String getFechaVenColegiado()
       {
          return this.fechaVenColegiado;
       }
    
       public void setFechaVenColegiado(java.lang.String fechaVenColegiado)
       {
          this.fechaVenColegiado = fechaVenColegiado;
       }
    
       public java.lang.String getBreveDesc()
       {
          return this.breveDesc;
       }
    
       public void setBreveDesc(java.lang.String breveDesc)
       {
          this.breveDesc = breveDesc;
       }
    
       public java.lang.String getCantidadPoste1()
       {
          return this.cantidadPoste1;
       }
    
       public void setCantidadPoste1(java.lang.String cantidadPoste1)
       {
          this.cantidadPoste1 = cantidadPoste1;
       }
    
       public java.lang.String getLongitudPoste1()
       {
          return this.longitudPoste1;
       }
    
       public void setLongitudPoste1(java.lang.String longitudPoste1)
       {
          this.longitudPoste1 = longitudPoste1;
       }
    
       public java.lang.String getMaterialPoste1()
       {
          return this.materialPoste1;
       }
    
       public void setMaterialPoste1(java.lang.String materialPoste1)
       {
          this.materialPoste1 = materialPoste1;
       }
    
       public java.lang.String getCantidadPoste2()
       {
          return this.cantidadPoste2;
       }
    
       public void setCantidadPoste2(java.lang.String cantidadPoste2)
       {
          this.cantidadPoste2 = cantidadPoste2;
       }
    
       public java.lang.String getLongitudPoste2()
       {
          return this.longitudPoste2;
       }
    
       public void setLongitudPoste2(java.lang.String longitudPoste2)
       {
          this.longitudPoste2 = longitudPoste2;
       }
    
       public java.lang.String getMaterialPoste2()
       {
          return this.materialPoste2;
       }
    
       public void setMaterialPoste2(java.lang.String materialPoste2)
       {
          this.materialPoste2 = materialPoste2;
       }
    
       public java.lang.String getCantidadPoste3()
       {
          return this.cantidadPoste3;
       }
    
       public void setCantidadPoste3(java.lang.String cantidadPoste3)
       {
          this.cantidadPoste3 = cantidadPoste3;
       }
    
       public java.lang.String getLongitudPoste3()
       {
          return this.longitudPoste3;
       }
    
       public void setLongitudPoste3(java.lang.String longitudPoste3)
       {
          this.longitudPoste3 = longitudPoste3;
       }
    
       public java.lang.String getMaterialPoste3()
       {
          return this.materialPoste3;
       }
    
       public void setMaterialPoste3(java.lang.String materialPoste3)
       {
          this.materialPoste3 = materialPoste3;
       }
    
       public java.lang.String getCantidadPoste4()
       {
          return this.cantidadPoste4;
       }
    
       public void setCantidadPoste4(java.lang.String cantidadPoste4)
       {
          this.cantidadPoste4 = cantidadPoste4;
       }
    
       public java.lang.String getLongitudPoste4()
       {
          return this.longitudPoste4;
       }
    
       public void setLongitudPoste4(java.lang.String longitudPoste4)
       {
          this.longitudPoste4 = longitudPoste4;
       }
    
       public java.lang.String getMaterialPoste4()
       {
          return this.materialPoste4;
       }
    
       public void setMaterialPoste4(java.lang.String materialPoste4)
       {
          this.materialPoste4 = materialPoste4;
       }
    
       public java.lang.String getCantidadPoste5()
       {
          return this.cantidadPoste5;
       }
    
       public void setCantidadPoste5(java.lang.String cantidadPoste5)
       {
          this.cantidadPoste5 = cantidadPoste5;
       }
    
       public java.lang.String getLongitudPoste5()
       {
          return this.longitudPoste5;
       }
    
       public void setLongitudPoste5(java.lang.String longitudPoste5)
       {
          this.longitudPoste5 = longitudPoste5;
       }
    
       public java.lang.String getMaterialPoste5()
       {
          return this.materialPoste5;
       }
    
       public void setMaterialPoste5(java.lang.String materialPoste5)
       {
          this.materialPoste5 = materialPoste5;
       }
    
       public java.lang.String getCantidadPoste6()
       {
          return this.cantidadPoste6;
       }
    
       public void setCantidadPoste6(java.lang.String cantidadPoste6)
       {
          this.cantidadPoste6 = cantidadPoste6;
       }
    
       public java.lang.String getLongitudPoste6()
       {
          return this.longitudPoste6;
       }
    
       public void setLongitudPoste6(java.lang.String longitudPoste6)
       {
          this.longitudPoste6 = longitudPoste6;
       }
    
       public java.lang.String getMaterialPoste6()
       {
          return this.materialPoste6;
       }
    
       public void setMaterialPoste6(java.lang.String materialPoste6)
       {
          this.materialPoste6 = materialPoste6;
       }
    
       public java.lang.String getResolucion()
       {
          return this.resolucion;
       }
    
       public void setResolucion(java.lang.String resolucion)
       {
          this.resolucion = resolucion;
       }
    
       public ObjectCoordenadas(java.lang.String xmts01, java.lang.String ymts01,
             java.lang.String xmts02, java.lang.String ymts02,
             java.lang.String xmts03, java.lang.String ymts03,
             java.lang.String xmts04, java.lang.String ymts04,
             java.lang.String xmts05, java.lang.String ymts05,
             java.lang.String xmts06, java.lang.String ymts06,
             java.lang.String xmts07, java.lang.String ymts07,
             java.lang.String xmts08, java.lang.String ymts08,
             java.lang.String xmts09, java.lang.String ymts09,
             java.lang.String xmts10, java.lang.String ymts10,
             java.lang.String xmts11, java.lang.String ymts11,
             java.lang.String xmts12, java.lang.String ymts12,
             java.lang.String xmts13, java.lang.String ymts13,
             java.lang.String xmts14, java.lang.String ymts14,
             java.lang.String xmts15, java.lang.String ymts15,
             java.lang.String xmts16, java.lang.String ymts16,
             java.lang.String xmts17, java.lang.String ymts17,
             java.lang.String xmts18, java.lang.String ymts18,
             java.lang.String xmts19, java.lang.String ymts19,
             java.lang.String xmts20, java.lang.String ymts20,
             java.lang.String tipoMedicion, java.lang.String matricula,
             java.lang.String faseUtilizar, java.lang.String nombreIng,
             java.lang.String numColegiado, java.lang.String telefonoIng,
             java.lang.String numConsColegiado, java.lang.String fechaVenColegiado,
             java.lang.String breveDesc, java.lang.String cantidadPoste1,
             java.lang.String longitudPoste1, java.lang.String materialPoste1,
             java.lang.String cantidadPoste2, java.lang.String longitudPoste2,
             java.lang.String materialPoste2, java.lang.String cantidadPoste3,
             java.lang.String longitudPoste3, java.lang.String materialPoste3,
             java.lang.String cantidadPoste4, java.lang.String longitudPoste4,
             java.lang.String materialPoste4, java.lang.String cantidadPoste5,
             java.lang.String longitudPoste5, java.lang.String materialPoste5,
             java.lang.String cantidadPoste6, java.lang.String longitudPoste6,
             java.lang.String materialPoste6, java.lang.String resolucion)
       {
          this.xmts01 = xmts01;
          this.ymts01 = ymts01;
          this.xmts02 = xmts02;
          this.ymts02 = ymts02;
          this.xmts03 = xmts03;
          this.ymts03 = ymts03;
          this.xmts04 = xmts04;
          this.ymts04 = ymts04;
          this.xmts05 = xmts05;
          this.ymts05 = ymts05;
          this.xmts06 = xmts06;
          this.ymts06 = ymts06;
          this.xmts07 = xmts07;
          this.ymts07 = ymts07;
          this.xmts08 = xmts08;
          this.ymts08 = ymts08;
          this.xmts09 = xmts09;
          this.ymts09 = ymts09;
          this.xmts10 = xmts10;
          this.ymts10 = ymts10;
          this.xmts11 = xmts11;
          this.ymts11 = ymts11;
          this.xmts12 = xmts12;
          this.ymts12 = ymts12;
          this.xmts13 = xmts13;
          this.ymts13 = ymts13;
          this.xmts14 = xmts14;
          this.ymts14 = ymts14;
          this.xmts15 = xmts15;
          this.ymts15 = ymts15;
          this.xmts16 = xmts16;
          this.ymts16 = ymts16;
          this.xmts17 = xmts17;
          this.ymts17 = ymts17;
          this.xmts18 = xmts18;
          this.ymts18 = ymts18;
          this.xmts19 = xmts19;
          this.ymts19 = ymts19;
          this.xmts20 = xmts20;
          this.ymts20 = ymts20;
          this.tipoMedicion = tipoMedicion;
          this.matricula = matricula;
          this.faseUtilizar = faseUtilizar;
          this.nombreIng = nombreIng;
          this.numColegiado = numColegiado;
          this.telefonoIng = telefonoIng;
          this.numConsColegiado = numConsColegiado;
          this.fechaVenColegiado = fechaVenColegiado;
          this.breveDesc = breveDesc;
          this.cantidadPoste1 = cantidadPoste1;
          this.longitudPoste1 = longitudPoste1;
          this.materialPoste1 = materialPoste1;
          this.cantidadPoste2 = cantidadPoste2;
          this.longitudPoste2 = longitudPoste2;
          this.materialPoste2 = materialPoste2;
          this.cantidadPoste3 = cantidadPoste3;
          this.longitudPoste3 = longitudPoste3;
          this.materialPoste3 = materialPoste3;
          this.cantidadPoste4 = cantidadPoste4;
          this.longitudPoste4 = longitudPoste4;
          this.materialPoste4 = materialPoste4;
          this.cantidadPoste5 = cantidadPoste5;
          this.longitudPoste5 = longitudPoste5;
          this.materialPoste5 = materialPoste5;
          this.cantidadPoste6 = cantidadPoste6;
          this.longitudPoste6 = longitudPoste6;
          this.materialPoste6 = materialPoste6;
          this.resolucion = resolucion;
       }
    
       public ObjectCoordenadas(java.lang.Long id, java.lang.String caso)
       {
          this.id = id;
          this.caso = caso;
       }
    
       public java.lang.String getXmts21()
       {
          return this.xmts21;
       }
    
       public void setXmts21(java.lang.String xmts21)
       {
          this.xmts21 = xmts21;
       }
    
       public java.lang.String getYmts21()
       {
          return this.ymts21;
       }
    
       public void setYmts21(java.lang.String ymts21)
       {
          this.ymts21 = ymts21;
       }
    
       public java.lang.String getXmts22()
       {
          return this.xmts22;
       }
    
       public void setXmts22(java.lang.String xmts22)
       {
          this.xmts22 = xmts22;
       }
    
       public java.lang.String getYmts22()
       {
          return this.ymts22;
       }
    
       public void setYmts22(java.lang.String ymts22)
       {
          this.ymts22 = ymts22;
       }
    
       public java.lang.String getXmts23()
       {
          return this.xmts23;
       }
    
       public void setXmts23(java.lang.String xmts23)
       {
          this.xmts23 = xmts23;
       }
    
       public java.lang.String getYmts23()
       {
          return this.ymts23;
       }
    
       public void setYmts23(java.lang.String ymts23)
       {
          this.ymts23 = ymts23;
       }
    
       public java.lang.String getXmts24()
       {
          return this.xmts24;
       }
    
       public void setXmts24(java.lang.String xmts24)
       {
          this.xmts24 = xmts24;
       }
    
       public java.lang.String getXmts25()
       {
          return this.xmts25;
       }
    
       public void setXmts25(java.lang.String xmts25)
       {
          this.xmts25 = xmts25;
       }
    
       public java.lang.String getYmts25()
       {
          return this.ymts25;
       }
    
       public void setYmts25(java.lang.String ymts25)
       {
          this.ymts25 = ymts25;
       }
    
       public java.lang.String getXmts26()
       {
          return this.xmts26;
       }
    
       public void setXmts26(java.lang.String xmts26)
       {
          this.xmts26 = xmts26;
       }
    
       public java.lang.String getYmts26()
       {
          return this.ymts26;
       }
    
       public void setYmts26(java.lang.String ymts26)
       {
          this.ymts26 = ymts26;
       }
    
       public java.lang.String getXmts27()
       {
          return this.xmts27;
       }
    
       public void setXmts27(java.lang.String xmts27)
       {
          this.xmts27 = xmts27;
       }
    
       public java.lang.String getXmts28()
       {
          return this.xmts28;
       }
    
       public void setXmts28(java.lang.String xmts28)
       {
          this.xmts28 = xmts28;
       }
    
       public java.lang.String getYmts28()
       {
          return this.ymts28;
       }
    
       public void setYmts28(java.lang.String ymts28)
       {
          this.ymts28 = ymts28;
       }
    
       public java.lang.String getXmts29()
       {
          return this.xmts29;
       }
    
       public void setXmts29(java.lang.String xmts29)
       {
          this.xmts29 = xmts29;
       }
    
       public java.lang.String getYmts29()
       {
          return this.ymts29;
       }
    
       public void setYmts29(java.lang.String ymts29)
       {
          this.ymts29 = ymts29;
       }
    
       public java.lang.String getXmts30()
       {
          return this.xmts30;
       }
    
       public void setXmts30(java.lang.String xmts30)
       {
          this.xmts30 = xmts30;
       }
    
       public java.lang.String getYmts30()
       {
          return this.ymts30;
       }
    
       public void setYmts30(java.lang.String ymts30)
       {
          this.ymts30 = ymts30;
       }
    
       public java.lang.String getYmts24()
       {
          return this.ymts24;
       }
    
       public void setYmts24(java.lang.String ymts24)
       {
          this.ymts24 = ymts24;
       }
    
       public java.lang.String getYmts27()
       {
          return this.ymts27;
       }
    
       public void setYmts27(java.lang.String ymts27)
       {
          this.ymts27 = ymts27;
       }
    
       public ObjectCoordenadas(java.lang.Long id, java.lang.String caso,
             java.lang.String xmts01, java.lang.String ymts01,
             java.lang.String xmts02, java.lang.String ymts02,
             java.lang.String xmts03, java.lang.String ymts03,
             java.lang.String xmts04, java.lang.String ymts04,
             java.lang.String xmts05, java.lang.String ymts05,
             java.lang.String xmts06, java.lang.String ymts06,
             java.lang.String xmts07, java.lang.String ymts07,
             java.lang.String xmts08, java.lang.String ymts08,
             java.lang.String xmts09, java.lang.String ymts09,
             java.lang.String xmts10, java.lang.String ymts10,
             java.lang.String xmts11, java.lang.String ymts11,
             java.lang.String xmts12, java.lang.String ymts12,
             java.lang.String xmts13, java.lang.String ymts13,
             java.lang.String xmts14, java.lang.String ymts14,
             java.lang.String xmts15, java.lang.String ymts15,
             java.lang.String xmts16, java.lang.String ymts16,
             java.lang.String xmts17, java.lang.String ymts17,
             java.lang.String xmts18, java.lang.String ymts18,
             java.lang.String xmts19, java.lang.String ymts19,
             java.lang.String xmts20, java.lang.String ymts20,
             java.lang.String tipoMedicion, java.lang.String matricula,
             java.lang.String faseUtilizar, java.lang.String nombreIng,
             java.lang.String numColegiado, java.lang.String telefonoIng,
             java.lang.String numConsColegiado, java.lang.String fechaVenColegiado,
             java.lang.String breveDesc, java.lang.String cantidadPoste1,
             java.lang.String longitudPoste1, java.lang.String materialPoste1,
             java.lang.String cantidadPoste2, java.lang.String longitudPoste2,
             java.lang.String materialPoste2, java.lang.String cantidadPoste3,
             java.lang.String longitudPoste3, java.lang.String materialPoste3,
             java.lang.String cantidadPoste4, java.lang.String longitudPoste4,
             java.lang.String materialPoste4, java.lang.String cantidadPoste5,
             java.lang.String longitudPoste5, java.lang.String materialPoste5,
             java.lang.String cantidadPoste6, java.lang.String longitudPoste6,
             java.lang.String materialPoste6, java.lang.String resolucion,
             java.lang.String xmts21, java.lang.String ymts21,
             java.lang.String xmts22, java.lang.String ymts22,
             java.lang.String xmts23, java.lang.String ymts23,
             java.lang.String xmts24, java.lang.String xmts25,
             java.lang.String ymts25, java.lang.String xmts26,
             java.lang.String ymts26, java.lang.String xmts27,
             java.lang.String xmts28, java.lang.String ymts28,
             java.lang.String xmts29, java.lang.String ymts29,
             java.lang.String xmts30, java.lang.String ymts30,
             java.lang.String ymts24, java.lang.String ymts27)
       {
          this.id = id;
          this.caso = caso;
          this.xmts01 = xmts01;
          this.ymts01 = ymts01;
          this.xmts02 = xmts02;
          this.ymts02 = ymts02;
          this.xmts03 = xmts03;
          this.ymts03 = ymts03;
          this.xmts04 = xmts04;
          this.ymts04 = ymts04;
          this.xmts05 = xmts05;
          this.ymts05 = ymts05;
          this.xmts06 = xmts06;
          this.ymts06 = ymts06;
          this.xmts07 = xmts07;
          this.ymts07 = ymts07;
          this.xmts08 = xmts08;
          this.ymts08 = ymts08;
          this.xmts09 = xmts09;
          this.ymts09 = ymts09;
          this.xmts10 = xmts10;
          this.ymts10 = ymts10;
          this.xmts11 = xmts11;
          this.ymts11 = ymts11;
          this.xmts12 = xmts12;
          this.ymts12 = ymts12;
          this.xmts13 = xmts13;
          this.ymts13 = ymts13;
          this.xmts14 = xmts14;
          this.ymts14 = ymts14;
          this.xmts15 = xmts15;
          this.ymts15 = ymts15;
          this.xmts16 = xmts16;
          this.ymts16 = ymts16;
          this.xmts17 = xmts17;
          this.ymts17 = ymts17;
          this.xmts18 = xmts18;
          this.ymts18 = ymts18;
          this.xmts19 = xmts19;
          this.ymts19 = ymts19;
          this.xmts20 = xmts20;
          this.ymts20 = ymts20;
          this.tipoMedicion = tipoMedicion;
          this.matricula = matricula;
          this.faseUtilizar = faseUtilizar;
          this.nombreIng = nombreIng;
          this.numColegiado = numColegiado;
          this.telefonoIng = telefonoIng;
          this.numConsColegiado = numConsColegiado;
          this.fechaVenColegiado = fechaVenColegiado;
          this.breveDesc = breveDesc;
          this.cantidadPoste1 = cantidadPoste1;
          this.longitudPoste1 = longitudPoste1;
          this.materialPoste1 = materialPoste1;
          this.cantidadPoste2 = cantidadPoste2;
          this.longitudPoste2 = longitudPoste2;
          this.materialPoste2 = materialPoste2;
          this.cantidadPoste3 = cantidadPoste3;
          this.longitudPoste3 = longitudPoste3;
          this.materialPoste3 = materialPoste3;
          this.cantidadPoste4 = cantidadPoste4;
          this.longitudPoste4 = longitudPoste4;
          this.materialPoste4 = materialPoste4;
          this.cantidadPoste5 = cantidadPoste5;
          this.longitudPoste5 = longitudPoste5;
          this.materialPoste5 = materialPoste5;
          this.cantidadPoste6 = cantidadPoste6;
          this.longitudPoste6 = longitudPoste6;
          this.materialPoste6 = materialPoste6;
          this.resolucion = resolucion;
          this.xmts21 = xmts21;
          this.ymts21 = ymts21;
          this.xmts22 = xmts22;
          this.ymts22 = ymts22;
          this.xmts23 = xmts23;
          this.ymts23 = ymts23;
          this.xmts24 = xmts24;
          this.xmts25 = xmts25;
          this.ymts25 = ymts25;
          this.xmts26 = xmts26;
          this.ymts26 = ymts26;
          this.xmts27 = xmts27;
          this.xmts28 = xmts28;
          this.ymts28 = ymts28;
          this.xmts29 = xmts29;
          this.ymts29 = ymts29;
          this.xmts30 = xmts30;
          this.ymts30 = ymts30;
          this.ymts24 = ymts24;
          this.ymts27 = ymts27;
       }
    
    }