package ouenerguate.dictamen;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class ObjectPruebaDictamen implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "OBJECTPRUEBADICTAMEN_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "OBJECTPRUEBADICTAMEN_ID_SEQ", name = "OBJECTPRUEBADICTAMEN_ID_GENERATOR")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label(value = "Prueba")
   private java.lang.String prueba;

   public ObjectPruebaDictamen()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getPrueba()
   {
      return this.prueba;
   }

   public void setPrueba(java.lang.String prueba)
   {
      this.prueba = prueba;
   }

   public ObjectPruebaDictamen(java.lang.Long id, java.lang.String prueba)
   {
      this.id = id;
      this.prueba = prueba;
   }

}