package ouenerguate.dictamen;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class ObjectTransformadores implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "OBJECTTRANSFORMADORES_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "OBJECTTRANSFORMADORES_ID_SEQ", name = "OBJECTTRANSFORMADORES_ID_GENERATOR")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label(value = "caso")
      private java.lang.String caso;

    @org.kie.api.definition.type.Label(value = "cantidad10kva")
   private java.lang.String cantidad10kva;
   @org.kie.api.definition.type.Label(value = "cantidad25kva")
   private java.lang.String cantidad25kva;
   @org.kie.api.definition.type.Label(value = "cantidad50kva")
   private java.lang.String cantidad50kva;
   @org.kie.api.definition.type.Label(value = "cantidad75kva")
   private java.lang.String cantidad75kva;
   @org.kie.api.definition.type.Label(value = "cantidadOtros")
   private java.lang.String cantidadOtros;
   @org.kie.api.definition.type.Label(value = "tipo10kva")
   private java.lang.String tipo10kva;
   @org.kie.api.definition.type.Label(value = "tipo25kva")
   private java.lang.String tipo25kva;
   @org.kie.api.definition.type.Label(value = "tipo50kva")
   private java.lang.String tipo50kva;
   @org.kie.api.definition.type.Label(value = "tipo75kva")
   private java.lang.String tipo75kva;
   @org.kie.api.definition.type.Label(value = "potenciaTotal")
   private java.lang.String potenciaTotal;
   @org.kie.api.definition.type.Label(value = "descripcionTranforma")
   private java.lang.String descripcionTranforma;
   @org.kie.api.definition.type.Label(value = "longCircuitoMedia")
   private java.lang.String longCircuitoMedia;
   @org.kie.api.definition.type.Label(value = "longCircuitoBaja")
   private java.lang.String longCircuitoBaja;
   
   
 
   public ObjectTransformadores()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getCaso()
   {
      return this.caso;
   }

   public void setCaso(java.lang.String caso)
   {
      this.caso = caso;
   }
   
   
   public java.lang.String getCantidad10kva()
   {
      return this.cantidad10kva;
   }

   public void setCantidad10kva(java.lang.String cantidad10kva)
   {
      this.cantidad10kva = cantidad10kva;
   }

   public java.lang.String getCantidad25kva()
   {
      return this.cantidad25kva;
   }

   public void setCantidad25kva(java.lang.String cantidad25kva)
   {
      this.cantidad25kva = cantidad25kva;
   }

   public java.lang.String getCantidad50kva()
   {
      return this.cantidad50kva;
   }

   public void setCantidad50kva(java.lang.String cantidad50kva)
   {
      this.cantidad50kva = cantidad50kva;
   }

   public java.lang.String getCantidad75kva()
   {
      return this.cantidad75kva;
   }

   public void setCantidad75kva(java.lang.String cantidad75kva)
   {
      this.cantidad75kva = cantidad75kva;
   }

   public java.lang.String getCantidadOtros()
   {
      return this.cantidadOtros;
   }

   public void setCantidadOtros(java.lang.String cantidadOtros)
   {
      this.cantidadOtros = cantidadOtros;
   }

   public java.lang.String getTipo10kva()
   {
      return this.tipo10kva;
   }

   public void setTipo10kva(java.lang.String tipo10kva)
   {
      this.tipo10kva = tipo10kva;
   }

   public java.lang.String getTipo25kva()
   {
      return this.tipo25kva;
   }

   public void setTipo25kva(java.lang.String tipo25kva)
   {
      this.tipo25kva = tipo25kva;
   }

   public java.lang.String getTipo50kva()
   {
      return this.tipo50kva;
   }

   public void setTipo50kva(java.lang.String tipo50kva)
   {
      this.tipo50kva = tipo50kva;
   }

   public java.lang.String getTipo75kva()
   {
      return this.tipo75kva;
   }

   public void setTipo75kva(java.lang.String tipo75kva)
   {
      this.tipo75kva = tipo75kva;
   }

   public java.lang.String getPotenciaTotal()
   {
      return this.potenciaTotal;
   }

   public void setPotenciaTotal(java.lang.String potenciaTotal)
   {
      this.potenciaTotal = potenciaTotal;
   }

   public java.lang.String getDescripcionTranforma()
   {
      return this.descripcionTranforma;
   }

   public void setDescripcionTranforma(java.lang.String descripcionTranforma)
   {
      this.descripcionTranforma = descripcionTranforma;
   }

   public java.lang.String getLongCircuitoMedia()
   {
      return this.longCircuitoMedia;
   }

   public void setLongCircuitoMedia(java.lang.String longCircuitoMedia)
   {
      this.longCircuitoMedia = longCircuitoMedia;
   }

   public java.lang.String getLongCircuitoBaja()
   {
      return this.longCircuitoBaja;
   }

   public void setLongCircuitoBaja(java.lang.String longCircuitoBaja)
   {
      this.longCircuitoBaja = longCircuitoBaja;
   }

   public ObjectTransformadores(java.lang.String cantidad10kva,
         java.lang.String cantidad25kva, java.lang.String cantidad50kva,
         java.lang.String cantidad75kva, java.lang.String cantidadOtros,
         java.lang.String tipo10kva, java.lang.String tipo25kva,
         java.lang.String tipo50kva, java.lang.String tipo75kva,
         java.lang.String potenciaTotal,
         java.lang.String descripcionTranforma,
         java.lang.String longCircuitoMedia,
         java.lang.String longCircuitoBaja)
   {
      this.cantidad10kva = cantidad10kva;
      this.cantidad25kva = cantidad25kva;
      this.cantidad50kva = cantidad50kva;
      this.cantidad75kva = cantidad75kva;
      this.cantidadOtros = cantidadOtros;
      this.tipo10kva = tipo10kva;
      this.tipo25kva = tipo25kva;
      this.tipo50kva = tipo50kva;
      this.tipo75kva = tipo75kva;
      this.potenciaTotal = potenciaTotal;
      this.descripcionTranforma = descripcionTranforma;
      this.longCircuitoMedia = longCircuitoMedia;
      this.longCircuitoBaja = longCircuitoBaja;
   }




   public ObjectTransformadores(java.lang.Long id, java.lang.String caso)
   {
      this.id = id;
      this.caso = caso;
   }

}