package ouenerguate.dictamen;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class ObjectSolicitudDictamen implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "OBJECTSOLICITUDDICTAMEN_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "OBJECTSOLICITUDDICTAMEN_ID_SEQ", name = "OBJECTSOLICITUDDICTAMEN_ID_GENERATOR")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label("caso")
   private java.lang.String caso;

   @org.kie.api.definition.type.Label("lugar")
   private java.lang.String lugar;

   @org.kie.api.definition.type.Label("fecha")
   private java.lang.String fecha;

   @org.kie.api.definition.type.Label("empresa")
   private java.lang.String empresa;

   @org.kie.api.definition.type.Label("telefono")
   private java.lang.String telefono;

   @org.kie.api.definition.type.Label("direRespuesta")
   private java.lang.String direRespuesta;

   @org.kie.api.definition.type.Label("capacidad")
   private java.lang.String capacidad;

   @org.kie.api.definition.type.Label("tension")
   private java.lang.String tension;

   @org.kie.api.definition.type.Label("nombreObra")
   private java.lang.String nombreObra;

   @org.kie.api.definition.type.Label("dirObra")
   private java.lang.String dirObra;

   @org.kie.api.definition.type.Label(value = "nit")
   private java.lang.String nit;

   public ObjectSolicitudDictamen()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getCaso()
   {
      return this.caso;
   }

   public void setCaso(java.lang.String caso)
   {
      this.caso = caso;
   }

   public java.lang.String getLugar()
   {
      return this.lugar;
   }

   public void setLugar(java.lang.String lugar)
   {
      this.lugar = lugar;
   }

   public java.lang.String getFecha()
   {
      return this.fecha;
   }

   public void setFecha(java.lang.String fecha)
   {
      this.fecha = fecha;
   }

   public java.lang.String getEmpresa()
   {
      return this.empresa;
   }

   public void setEmpresa(java.lang.String empresa)
   {
      this.empresa = empresa;
   }

   public java.lang.String getTelefono()
   {
      return this.telefono;
   }

   public void setTelefono(java.lang.String telefono)
   {
      this.telefono = telefono;
   }

   public java.lang.String getDireRespuesta()
   {
      return this.direRespuesta;
   }

   public void setDireRespuesta(java.lang.String direRespuesta)
   {
      this.direRespuesta = direRespuesta;
   }

   public java.lang.String getCapacidad()
   {
      return this.capacidad;
   }

   public void setCapacidad(java.lang.String capacidad)
   {
      this.capacidad = capacidad;
   }

   public java.lang.String getTension()
   {
      return this.tension;
   }

   public void setTension(java.lang.String tension)
   {
      this.tension = tension;
   }

   public java.lang.String getNombreObra()
   {
      return this.nombreObra;
   }

   public void setNombreObra(java.lang.String nombreObra)
   {
      this.nombreObra = nombreObra;
   }

   public java.lang.String getDirObra()
   {
      return this.dirObra;
   }

   public void setDirObra(java.lang.String dirObra)
   {
      this.dirObra = dirObra;
   }

   public java.lang.String getNit()
   {
      return this.nit;
   }

   public void setNit(java.lang.String nit)
   {
      this.nit = nit;
   }

   public ObjectSolicitudDictamen(java.lang.Long id, java.lang.String caso,
         java.lang.String lugar, java.lang.String fecha,
         java.lang.String empresa, java.lang.String telefono,
         java.lang.String direRespuesta, java.lang.String capacidad,
         java.lang.String tension, java.lang.String nombreObra,
         java.lang.String dirObra, java.lang.String nit)
   {
      this.id = id;
      this.caso = caso;
      this.lugar = lugar;
      this.fecha = fecha;
      this.empresa = empresa;
      this.telefono = telefono;
      this.direRespuesta = direRespuesta;
      this.capacidad = capacidad;
      this.tension = tension;
      this.nombreObra = nombreObra;
      this.dirObra = dirObra;
      this.nit = nit;
   }

}